decision_making:
  plugin: plugins.grape.GRAPE
  GRAPE:
    global_situational_awareness: True
    execute_movements_during_convergence: False
    initialize_partition: Distance 
    reinitialize_partition_on_completion: 

agents:
  quantity: 500
  locations:
    x_min: 0
    x_max: 1400
    y_min: 0
    y_max: 1000
    non_overlap_radius: 0 
  max_speed: 3
  max_accel: 0.1
  max_angular_speed: 0.3
  target_approaching_radius: 50
  work_rate: 1  # work rate for each agent (per 1.0/simulation.sampling_freq)
  communication_radius: 100
  situation_awareness_radius: 300

tasks:
  quantity: 10
  locations:
    x_min: 0
    x_max: 1400
    y_min: 0
    y_max: 1000
    non_overlap_radius: 0
  threshold_done_by_arrival: 10.0
  amounts:  # Added amounts range for tasks
    min: 60.0
    max: 6000.0

simulation:
  sampling_freq: 60.0
  agent_track_size: 100  
  screen_width: 1400 
  screen_height: 1000 
  debug_mode: False
  gif_recording_fps: 10
  task_visualisation_factor: 100  # visualization factor for tasks : 10 means converting 10 amount to 1 pixel
  profiling_mode: False
  rendering_mode: Screen  # Options: Screen; Terminal; None
  rendering_options: # Only works if `rendering_mode` is `Screen`
    agent_tail: True
    agent_communication_topology: True
    agent_situation_awareness_circle: False
    agent_id: False
    agent_assigned_task_id: False
    task_id: False
