# decision_making: # Case 1
#   plugin: plugins.grape.GRAPE
#   GRAPE:
#     execute_movements_during_convergence: True
#     cost_weight_factor: 0.5
#     social_inhibition_factor: 100.0
#     initialize_partition: Distance # Options: None; Distance      
#     reinitialize_partition_on_completion: Distance # Options: None; Distance; 

decision_making: # Case 2
  plugin: plugins.cbba.CBBA
  CBBA:  
    max_tasks_per_agent: 5 
    task_reward_discount_factor: 0.99 
    winngin_bid_discount_factor: 0.99999999 # Note: 1 is default. This factor might be required to be less than 1 for dynamic task generation scenario. 
    

# decision_making: # Case 3
#   plugin: plugins.simple.LocalSearch
#   LocalSearch:  
#     mode: MinDist  # Options: Random; MinDist; MaxUtil
#     weight_factor_cost: 10000.0 # Only used for `MaxUtil` mode


agents:
  behavior_tree_xml: default_bt.xml 
  quantity: 20
  locations:
    x_min: 0
    x_max: 1400
    y_min: 0
    y_max: 1000
    non_overlap_radius: 0 
  max_speed: 3  
  max_accel: 0.1
  max_angular_speed: 0.3
  target_approaching_radius: 50
  work_rate: 1  # work rate for each agent (per 1.0/simulation.sampling_freq)
  communication_radius: 100 # 0 represents "global", meaning that each agent can access to the information of all the other agents
  situation_awareness_radius: 500 # 0 represents "global", meaning that each agent can access to the information of all the tasks
  random_exploration_duration: 2.0

tasks:
  quantity: 200
  locations:
    x_min: 0
    x_max: 1400
    y_min: 0
    y_max: 1000
    non_overlap_radius: 0
  threshold_done_by_arrival: 10.0
  amounts:  # Added amounts range for tasks
    min: 6.0
    max: 60.0      
  dynamic_task_generation:
    enabled: True
    interval_seconds: 5
    max_generations: 3
    tasks_per_generation: 50

simulation:
  sampling_freq: 60.0
  agent_track_size: 100  
  screen_width: 1400 
  screen_height: 1000 
  debug_mode: False
  gif_recording_fps: 10
  task_visualisation_factor: 3  # visualization factor for tasks : 10 means converting 10 amount to 1 pixel
  profiling_mode: False
  time_recording_mode: True
  rendering_mode: Screen  # Options: Screen; Terminal; None
  rendering_options: # Only works if `rendering_mode` is `Screen`
    agent_tail: True
    agent_communication_topology: True
    agent_situation_awareness_circle: False
    agent_id: True
    agent_work_done: True
    agent_assigned_task_id: True
    agent_path_to_assigned_tasks: True
    task_id: False
