agents:
  quantity: 10
  locations:
    x_min: 0
    x_max: 1400
    y_min: 0
    y_max: 1000
    non_overlap_radius: 0 
  decision_making_module_path: plugins.random_assignment.RandomAssignment  
  # decision_making_module_path: plugins.my_decision_making_plugin.MyDecisionMakingClass  
  max_speed: 3
  max_accel: 0.1
  max_angular_speed: 0.3
  target_approaching_radius: 50

tasks:
  quantity: 30
  locations:
    x_min: 0
    x_max: 1400
    y_min: 0
    y_max: 1000
    non_overlap_radius: 0
  threshold_done_by_arrival: 5.0

simulation:
  sampling_freq: 60.0
  agent_track_size: 100  
  screen_width: 1400 
  screen_height: 1000 
  debug_mode: False
  gif_recording_fps: 10
